; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "1CArchiver"
#define MyAppPublisher "SC Oxvalprim SRL"
#define MyAppExeName "1CArchiver.exe"

; Valori implicite - build_script\build_win_common.bat le transmite prin /D
#ifndef MyAppVersion
  #define MyAppVersion "1.5"
#endif
#ifndef ProjectDir
  #define ProjectDir "C:\Qt_projects\1CArchiver"
#endif
#ifndef AppSourceDir
  #define AppSourceDir ProjectDir + "\build\1CArchiver_v" + MyAppVersion
#endif
#ifndef AppOutputDir
  #define AppOutputDir ProjectDir + "\build"
#endif
#ifndef AppOutputBase
  #define AppOutputBase "1CArchiver_v" + MyAppVersion + "_Windows_amd64"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{11BB6097-8F0A-44BF-83DB-D2823F1B079F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile={#ProjectDir}\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir={#AppOutputDir}
OutputBaseFilename={#AppOutputBase}
SetupIconFile={#ProjectDir}\icons\backup.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#AppSourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#AppSourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#AppSourceDir}\VC_redist.x64.exe"; Flags: dontcopy
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]

function InstallVCRedist(): Boolean;
var
  ResultCode: Integer;
begin
  Result :=
    ShellExec(
      '',
      ExpandConstant('{tmp}\VC_redist.x64.exe'),
      '/norestart',
      '',
      SW_SHOWNORMAL,
      ewWaitUntilTerminated,
      ResultCode
    );

  Log('VC++ installer exit code: ' + IntToStr(ResultCode));
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  ExtractTemporaryFile('VC_redist.x64.exe');
  InstallVCRedist();
end;

